export const LANGUAGE = "LANGUAGE";

export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const VERIFY_TOKEN_BEGIN = "VERIFY_TOKEN_BEGIN";
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
export const VERIFY_TOKEN_ERROR = "VERIFY_TOKEN_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_MATERIALS_CONSUMPTION_BEGIN =
  "GET_MATERIALS_CONSUMPTION_BEGIN";
export const GET_MATERIALS_CONSUMPTION_SUCCESS =
  "GET_MATERIALS_CONSUMPTION_SUCCESS";

export const GET_MATERIAL_INVENTORY_BEGIN = "GET_MATERIAL_INVENTORY_BEGIN";
export const GET_MATERIAL_INVENTORY_SUCCESS = "GET_MATERIAL_INVENTORY_SUCCESS";

export const GET_USERS_BEGIN = "GET_USERS_BEGIN";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_MODAL_CONFIRM = "OPEN_MODAL_CONFIRM";
export const CLOSE_MODAL_CONFIRM = "CLOSE_MODAL_CONFIRM";

// Stats
export const GET_DAILY_PRODUCTION_BEGIN = "GET_DAILY_PRODUCTION_BEGIN";
export const GET_DAILY_PRODUCTION_SUCCESS = "GET_DAILY_PRODUCTION_SUCCESS";
export const GET_DAILY_PRODUCTION_EMPTY = "GET_DAILY_PRODUCTION_EMPTY";

export const GET_MATERIAL_TOLERANCE_BEGIN = "GET_MATERIAL_TOLERANCE_BEGIN";
export const GET_MATERIAL_TOLERANCE_SUCCESS = "GET_MATERIAL_TOLERANCE_SUCCESS";

// Materials
export const GET_MATERIALS_BEGIN = "GET_MATERIALS_BEGIN";
export const GET_MATERIALS_SUCCESS = "GET_MATERIALS_SUCCESS";

export const CREATE_MATERIAL_BEGIN = "CREATE_MATERIAL_BEGIN";
export const CREATE_MATERIAL_SUCCESS = "CREATE_MATERIAL_SUCCESS";
export const CREATE_MATERIAL_ERROR = "CREATE_MATERIAL_ERROR";

export const SET_EDIT_MATERIAL = "SET_EDIT_MATERIAL";

export const EDIT_MATERIAL_BEGIN = "EDIT_MATERIAL_BEGIN";
export const EDIT_MATERIAL_SUCCESS = "EDIT_MATERIAL_SUCCESS";
export const EDIT_MATERIAL_ERROR = "EDIT_MATERIAL_ERROR";

export const DELETE_MATERIAL_BEGIN = "DELETE_MATERIAL_BEGIN";
export const DELETE_MATERIAL_SUCCESS = "DELETE_MATERIAL_SUCCESS";
export const DELETE_MATERIAL_ERROR = "DELETE_MATERIAL_ERROR";

// Formulas
export const GET_FORMULAS_BEGIN = "GET_FORMULAS_BEGIN";
export const GET_FORMULAS_SUCCESS = "GET_FORMULAS_SUCCESS";

export const CREATE_FORMULA_BEGIN = "CREATE_FORMULA_BEGIN";
export const CREATE_FORMULA_SUCCESS = "CREATE_FORMULA_SUCCESS";
export const CREATE_FORMULA_ERROR = "CREATE_FORMULA_ERROR";

export const SET_EDIT_FORMULA = "SET_EDIT_FORMULA";

export const EDIT_FORMULA_BEGIN = "EDIT_FORMULA_BEGIN";
export const EDIT_FORMULA_SUCCESS = "EDIT_FORMULA_SUCCESS";
export const EDIT_FORMULA_ERROR = "EDIT_FORMULA_ERROR";

export const DELETE_FORMULA_BEGIN = "DELETE_FORMULA_BEGIN";
export const DELETE_FORMULA_SUCCESS = "DELETE_FORMULA_SUCCESS";
export const DELETE_FORMULA_ERROR = "DELETE_FORMULA_ERROR";

// Warehouse
export const GET_WAREHOUSES_BEGIN = "GET_WAREHOUSES_BEGIN";
export const GET_WAREHOUSES_SUCCESS = "GET_WAREHOUSES_SUCCESS";
export const GET_WAREHOUSES_ERROR = "GET_WAREHOUSES_ERROR";

export const GET_WAREHOUSE_INVENTORY_BEGIN = "GET_WAREHOUSE_INVENTORY_BEGIN";
export const GET_WAREHOUSE_INVENTORY_SUCCESS =
  "GET_WAREHOUSE_INVENTORY_SUCCESS";
